FROM debian:bullseye-slim

ENV PYTHONUNBUFFERED 1

LABEL author="markmur88"
LABEL description="Dockerfile for Debian Bullseye"
LABEL version="1.0"

# Actualización e instalación de paquetes esenciales
RUN apt update && apt upgrade -y && apt install -y \
    python3 python3-venv python3-pip python3-dev python3-psycopg2 python3-psycopg2-binary \
    git curl wget gcc libffi-dev libssl-dev nodejs npm yarn nginx supervisor \
    postgresql postgresql-client postgresql-contrib libpq-dev \
    sudo openssh-server apt-transport-https ca-certificates software-properties-common \
    && apt autoremove -y && apt autoclean -y && apt clean -y

# Configuración de usuario
RUN useradd -m -s /bin/bash markmur88 && echo "markmur88:Ptf8454Jd55" | chpasswd \
    && usermod -aG sudo markmur88

USER markmur88

# Configuración de Docker
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt update && apt install -y docker-ce docker-ce-cli containerd.io \
    && sudo usermod -aG docker markmur88

# Configuración de SSH
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config \
    && sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords no/' /etc/ssh/sshd_config \
    && sed -i 's/#ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config \
    && sed -i 's/#UsePAM yes/UsePAM no/' /etc/ssh/sshd_config \
    && sed -i 's/#X11Forwarding yes/X11Forwarding no/' /etc/ssh/sshd_config \
    && sed -i 's/#PrintMotd yes/PrintMotd no/' /etc/ssh/sshd_config \
    && sed -i 's/#AuthorizedKeysFile/AuthorizedKeysFile/' /etc/ssh/sshd_config

RUN mkdir -p /home/markmur88/.ssh && touch /home/markmur88/.ssh/authorized_keys \
    && chmod 700 /home/markmur88/.ssh && chmod 600 /home/markmur88/.ssh/authorized_keys

# Configuración del proyecto
RUN mkdir -p /home/markmur88/conf3
WORKDIR /home/markmur88/conf3

# Copiar archivos del proyecto
COPY . /home/markmur88/conf3




