# coding: utf-8

"""
    dbapi-processingOrders

    Create a document processing order. Limited access for special consumers only.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.processing_orders_api import ProcessingOrdersApi


class TestProcessingOrdersApi(unittest.TestCase):
    """ProcessingOrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProcessingOrdersApi()

    def tearDown(self) -> None:
        pass

    def test_create_processing_orders(self) -> None:
        """Test case for create_processing_orders

        Create a processing order
        """
        pass

    def test_upload_document(self) -> None:
        """Test case for upload_document

        Upload a document image
        """
        pass


if __name__ == '__main__':
    unittest.main()
