# coding: utf-8

"""
    dbapi-sepaCreditTransfer

    Easily initiate SEPA credit transfer then if required cancel or get the status and get the details afterwards.

    The version of the OpenAPI document: v1
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.debtor import Debtor

class TestDebtor(unittest.TestCase):
    """Debtor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Debtor:
        """Test Debtor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Debtor`
        """
        model = Debtor()
        if include_optional:
            return Debtor(
                debtor_name = '',
                debtor_postal_address = openapi_client.models.address.Address(
                    country = 'DE', 
                    address_line = openapi_client.models.address_line.AddressLine(
                        street_and_house_number = '', 
                        zip_code_and_city = '', ), )
            )
        else:
            return Debtor(
                debtor_name = '',
        )
        """

    def testDebtor(self):
        """Test Debtor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
