# coding: utf-8

"""
    dbapi-sepaCreditTransfer

    Easily initiate SEPA credit transfer then if required cancel or get the status and get the details afterwards.

    The version of the OpenAPI document: v1
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sepa_credit_transfer_update_sca_request import SepaCreditTransferUpdateScaRequest

class TestSepaCreditTransferUpdateScaRequest(unittest.TestCase):
    """SepaCreditTransferUpdateScaRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SepaCreditTransferUpdateScaRequest:
        """Test SepaCreditTransferUpdateScaRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SepaCreditTransferUpdateScaRequest`
        """
        model = SepaCreditTransferUpdateScaRequest()
        if include_optional:
            return SepaCreditTransferUpdateScaRequest(
                action = 'CREATE',
                auth_id = '232ed5b7-fc70-4c67-98bb-bf95b3300001'
            )
        else:
            return SepaCreditTransferUpdateScaRequest(
                action = 'CREATE',
                auth_id = '232ed5b7-fc70-4c67-98bb-bf95b3300001',
        )
        """

    def testSepaCreditTransferUpdateScaRequest(self):
        """Test SepaCreditTransferUpdateScaRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
