# coding: utf-8

"""
    dbapi-sepaCreditTransfer

    Easily initiate SEPA credit transfer then if required cancel or get the status and get the details afterwards.

    The version of the OpenAPI document: v1
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sepa_credit_transfer_details_response import SepaCreditTransferDetailsResponse

class TestSepaCreditTransferDetailsResponse(unittest.TestCase):
    """SepaCreditTransferDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SepaCreditTransferDetailsResponse:
        """Test SepaCreditTransferDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SepaCreditTransferDetailsResponse`
        """
        model = SepaCreditTransferDetailsResponse()
        if include_optional:
            return SepaCreditTransferDetailsResponse(
                transaction_status = 'ACCP',
                payment_id = '232ed5b7-fc70-4c67-98bb-bf95b3300001',
                purpose_code = '0123',
                requested_execution_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                debtor = openapi_client.models.debtor.Debtor(
                    debtor_name = '', 
                    debtor_postal_address = openapi_client.models.address.Address(
                        country = 'DE', 
                        address_line = openapi_client.models.address_line.AddressLine(
                            street_and_house_number = '', 
                            zip_code_and_city = '', ), ), ),
                debtor_account = openapi_client.models.debtor_account.DebtorAccount(
                    iban = 'AE80GCKEC0L3O4GI7XHK0J', 
                    currency = 'EUR', ),
                creditor_agent = openapi_client.models.creditor_agent.CreditorAgent(
                    financial_institution_id = '', ),
                creditor = openapi_client.models.creditor.Creditor(
                    creditor_name = '', 
                    creditor_postal_address = openapi_client.models.address.Address(
                        country = 'DE', 
                        address_line = openapi_client.models.address_line.AddressLine(
                            street_and_house_number = '', 
                            zip_code_and_city = '', ), ), ),
                creditor_account = openapi_client.models.creditor_account.CreditorAccount(
                    iban = 'AE80GCKEC0L3O4GI7XHK0J', 
                    currency = 'EUR', ),
                payment_identification = openapi_client.models.payment_identification.PaymentIdentification(
                    end_to_end_id = 'zA9LCSLv1C1ylmgd0.Y2T', 
                    instruction_id = 'zA9LCSLv1C1ylmgd0.Y2T', ),
                instructed_amount = openapi_client.models.instructed_amount.InstructedAmount(
                    amount = 58.13, 
                    currency = 'EUR', ),
                remittance_information_structured = '',
                remittance_information_unstructured = ''
            )
        else:
            return SepaCreditTransferDetailsResponse(
                transaction_status = 'ACCP',
                payment_id = '232ed5b7-fc70-4c67-98bb-bf95b3300001',
                purpose_code = '0123',
                requested_execution_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                debtor = openapi_client.models.debtor.Debtor(
                    debtor_name = '', 
                    debtor_postal_address = openapi_client.models.address.Address(
                        country = 'DE', 
                        address_line = openapi_client.models.address_line.AddressLine(
                            street_and_house_number = '', 
                            zip_code_and_city = '', ), ), ),
                debtor_account = openapi_client.models.debtor_account.DebtorAccount(
                    iban = 'AE80GCKEC0L3O4GI7XHK0J', 
                    currency = 'EUR', ),
                creditor_agent = openapi_client.models.creditor_agent.CreditorAgent(
                    financial_institution_id = '', ),
                creditor = openapi_client.models.creditor.Creditor(
                    creditor_name = '', 
                    creditor_postal_address = openapi_client.models.address.Address(
                        country = 'DE', 
                        address_line = openapi_client.models.address_line.AddressLine(
                            street_and_house_number = '', 
                            zip_code_and_city = '', ), ), ),
                creditor_account = openapi_client.models.creditor_account.CreditorAccount(
                    iban = 'AE80GCKEC0L3O4GI7XHK0J', 
                    currency = 'EUR', ),
                instructed_amount = openapi_client.models.instructed_amount.InstructedAmount(
                    amount = 58.13, 
                    currency = 'EUR', ),
                remittance_information_structured = '',
                remittance_information_unstructured = '',
        )
        """

    def testSepaCreditTransferDetailsResponse(self):
        """Test SepaCreditTransferDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
