# coding: utf-8

"""
    dbapi-sepaCreditTransfer

    Easily initiate SEPA credit transfer then if required cancel or get the status and get the details afterwards.

    The version of the OpenAPI document: v1
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_identification import PaymentIdentification

class TestPaymentIdentification(unittest.TestCase):
    """PaymentIdentification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentIdentification:
        """Test PaymentIdentification
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentIdentification`
        """
        model = PaymentIdentification()
        if include_optional:
            return PaymentIdentification(
                end_to_end_id = 'zA9LCSLv1C1ylmgd0.Y2T',
                instruction_id = 'zA9LCSLv1C1ylmgd0.Y2T'
            )
        else:
            return PaymentIdentification(
        )
        """

    def testPaymentIdentification(self):
        """Test PaymentIdentification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
