# coding: utf-8

"""
    dbapi-sepaCreditTransfer

    Easily initiate SEPA credit transfer then if required cancel or get the status and get the details afterwards.

    The version of the OpenAPI document: v1
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.get_sepa_credit_transfer_details_api import GetSepaCreditTransferDetailsApi


class TestGetSepaCreditTransferDetailsApi(unittest.TestCase):
    """GetSepaCreditTransferDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetSepaCreditTransferDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_payment_id_get(self) -> None:
        """Test case for payment_id_get

        Retrieve the Sepa Credit Transfer details
        """
        pass


if __name__ == '__main__':
    unittest.main()
