# Generated by Django 5.2 on 2025-05-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0002_remove_sepacredittransfer_payment_type_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='customer_id',
            field=models.CharField(default='090512DEUTDEFFXXX886479', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_name',
            field=models.CharField(default='MIRYA TRADING CO LTD', max_length=70, unique=True),
        ),
    ]
