# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_type_item import ChallengeTypeItem

class TestChallengeTypeItem(unittest.TestCase):
    """ChallengeTypeItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeTypeItem:
        """Test ChallengeTypeItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeTypeItem`
        """
        model = ChallengeTypeItem()
        if include_optional:
            return ChallengeTypeItem(
                type = 'SINGLE',
                metadata = None
            )
        else:
            return ChallengeTypeItem(
                type = 'SINGLE',
        )
        """

    def testChallengeTypeItem(self):
        """Test ChallengeTypeItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
