# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.one_time_passwords_api import OneTimePasswordsApi


class TestOneTimePasswordsApi(unittest.TestCase):
    """OneTimePasswordsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OneTimePasswordsApi()

    def tearDown(self) -> None:
        pass

    def test_create_challenge_v2(self) -> None:
        """Test case for create_challenge_v2

        Generate a one-time password challenge request.
        """
        pass

    def test_get_challenge_methods_v2(self) -> None:
        """Test case for get_challenge_methods_v2

        This service returns the customers one-time-password challenge methods.
        """
        pass

    def test_switch_method_v2(self) -> None:
        """Test case for switch_method_v2

        Switch authorization method
        """
        pass

    def test_verify_challenge_v2(self) -> None:
        """Test case for verify_challenge_v2

        Reply to a one-time password challenge request.
        """
        pass


if __name__ == '__main__':
    unittest.main()
