# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_add_ons import OrderAddOns

class TestOrderAddOns(unittest.TestCase):
    """OrderAddOns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderAddOns:
        """Test OrderAddOns
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderAddOns`
        """
        model = OrderAddOns()
        if include_optional:
            return OrderAddOns(
                expiry_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                restriction = 'GOOD_TILL_DATE'
            )
        else:
            return OrderAddOns(
        )
        """

    def testOrderAddOns(self):
        """Test OrderAddOns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
