# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_activity_type import OrderActivityType

class TestOrderActivityType(unittest.TestCase):
    """OrderActivityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderActivityType(self):
        """Test OrderActivityType"""
        # inst = OrderActivityType()

if __name__ == '__main__':
    unittest.main()
