# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_request_data_instant_sepa_credit_transfers import ChallengeRequestDataInstantSepaCreditTransfers

class TestChallengeRequestDataInstantSepaCreditTransfers(unittest.TestCase):
    """ChallengeRequestDataInstantSepaCreditTransfers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeRequestDataInstantSepaCreditTransfers:
        """Test ChallengeRequestDataInstantSepaCreditTransfers
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeRequestDataInstantSepaCreditTransfers`
        """
        model = ChallengeRequestDataInstantSepaCreditTransfers()
        if include_optional:
            return ChallengeRequestDataInstantSepaCreditTransfers(
                type = 'challengeRequestDataInstantSepaCreditTransfers',
                target_iban = 'AE80GCKEC0L3O4GI7XHK0J',
                amount_currency = 'EUR',
                amount_value = 1.337
            )
        else:
            return ChallengeRequestDataInstantSepaCreditTransfers(
                type = 'challengeRequestDataInstantSepaCreditTransfers',
                target_iban = 'AE80GCKEC0L3O4GI7XHK0J',
                amount_currency = 'EUR',
                amount_value = 1.337,
        )
        """

    def testChallengeRequestDataInstantSepaCreditTransfers(self):
        """Test ChallengeRequestDataInstantSepaCreditTransfers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
