# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_request_data_securities_order_entry import ChallengeRequestDataSecuritiesOrderEntry

class TestChallengeRequestDataSecuritiesOrderEntry(unittest.TestCase):
    """ChallengeRequestDataSecuritiesOrderEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeRequestDataSecuritiesOrderEntry:
        """Test ChallengeRequestDataSecuritiesOrderEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeRequestDataSecuritiesOrderEntry`
        """
        model = ChallengeRequestDataSecuritiesOrderEntry()
        if include_optional:
            return ChallengeRequestDataSecuritiesOrderEntry(
                type = 'challengeRequestDataSecuritiesOrderEntry',
                security_account_id = '048072888001',
                security_id = 'W8Q6ZG',
                quantity = 0,
                activity_type = 'SELL',
                order_limit = openapi_client.models.order_limit.OrderLimit(
                    limit_price = 0, 
                    stop_price = 0, ),
                add_ons = openapi_client.models.order_add_ons.OrderAddOns(
                    expiry_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    restriction = 'GOOD_TILL_DATE', )
            )
        else:
            return ChallengeRequestDataSecuritiesOrderEntry(
                type = 'challengeRequestDataSecuritiesOrderEntry',
                security_account_id = '048072888001',
                security_id = 'W8Q6ZG',
                quantity = 0,
                activity_type = 'SELL',
        )
        """

    def testChallengeRequestDataSecuritiesOrderEntry(self):
        """Test ChallengeRequestDataSecuritiesOrderEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
