# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_start import ChallengeStart

class TestChallengeStart(unittest.TestCase):
    """ChallengeStart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeStart:
        """Test ChallengeStart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeStart`
        """
        model = ChallengeStart()
        if include_optional:
            return ChallengeStart(
                method = 'MTAN',
                request_type = 'TRANSFER_PARTNER_LEGI_DATA',
                request_data = None,
                language = 'de'
            )
        else:
            return ChallengeStart(
                method = 'MTAN',
                request_type = 'TRANSFER_PARTNER_LEGI_DATA',
                request_data = None,
        )
        """

    def testChallengeStart(self):
        """Test ChallengeStart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
