# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_request_data_securities_order_delete import ChallengeRequestDataSecuritiesOrderDelete

class TestChallengeRequestDataSecuritiesOrderDelete(unittest.TestCase):
    """ChallengeRequestDataSecuritiesOrderDelete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeRequestDataSecuritiesOrderDelete:
        """Test ChallengeRequestDataSecuritiesOrderDelete
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeRequestDataSecuritiesOrderDelete`
        """
        model = ChallengeRequestDataSecuritiesOrderDelete()
        if include_optional:
            return ChallengeRequestDataSecuritiesOrderDelete(
                type = 'challengeRequestDataSecuritiesOrderDelete',
                order_id = '',
                security_account_id = '048072888001'
            )
        else:
            return ChallengeRequestDataSecuritiesOrderDelete(
                type = 'challengeRequestDataSecuritiesOrderDelete',
                order_id = '',
                security_account_id = '048072888001',
        )
        """

    def testChallengeRequestDataSecuritiesOrderDelete(self):
        """Test ChallengeRequestDataSecuritiesOrderDelete"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
