# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_type_type import ChallengeTypeType

class TestChallengeTypeType(unittest.TestCase):
    """ChallengeTypeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChallengeTypeType(self):
        """Test ChallengeTypeType"""
        # inst = ChallengeTypeType()

if __name__ == '__main__':
    unittest.main()
