# Generated by Django 5.2 on 2025-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientid',
            name='clientId',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
