# Generated by Django 5.2 on 2025-05-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfersKID', to='gpt4.kid'),
        ),
    ]
