# Generated by Django 5.2 on 2025-05-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='mobile_phone_number',
            field=models.CharField(blank=True, help_text='Formato internacional, e.g. +4915123456789', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada técnicamente'), ('ACSP', 'En proceso'), ('ACSC', 'Ejecutada con éxito'), ('ACWC', 'Con advertencia'), ('ACWP', 'Pendiente de aprobación'), ('ACCC', 'Concluida'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente'), ('CREA', 'Creada')], max_length=10),
        ),
    ]
