# Generated by Django 5.2 on 2025-04-29 23:16

import api.gpt4.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='payment_id',
            field=models.CharField(default=api.gpt4.helpers.generate_unique_code, max_length=35, unique=True),
        ),
    ]
