# Generated by Django 5.2 on 2025-05-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0002_alter_creditoraccount_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada técnicamente'), ('ACSP', 'En proceso'), ('ACSC', 'Ejecutada con éxito'), ('ACWC', 'Con advertencia'), ('ACWP', 'Pendiente de aprobación'), ('ACCC', 'Concluida'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente'), ('CREA', 'Creada')], default='PDNG', max_length=10),
        ),
    ]
