# Generated by Django 5.2 on 2025-05-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0002_alter_transfer_kid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='remittance_information_structured',
        ),
    ]
