# Generated by Django 5.2 on 2025-05-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0002_debtor_mobile_phone_number_alter_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada técnicamente'), ('ACSP', 'En proceso'), ('ACSC', 'Ejecutada con éxito'), ('ACWC', 'Con advertencia'), ('ACWP', 'Pendiente de aprobación'), ('ACCC', 'Concluida'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente'), ('CREA', 'Creada')], default='CREA', max_length=10),
        ),
    ]
