# Generated by Django 5.2 on 2025-05-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0003_remove_transfer_remittance_information_structured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientid',
            name='clientId',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kid',
            name='kid',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
