# Generated by Django 5.2 on 2025-05-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0003_alter_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='customer_id',
            field=models.CharField(default='27CDBFRDE17BEH', max_length=35, unique=True),
        ),
    ]
