from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreditorAgent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, financial_institution_id=None):  # noqa: E501
        """CreditorAgent - a model defined in OpenAPI

        :param financial_institution_id: The financial_institution_id of this CreditorAgent.  # noqa: E501
        :type financial_institution_id: str
        """
        self.openapi_types = {
            'financial_institution_id': str
        }

        self.attribute_map = {
            'financial_institution_id': 'financialInstitutionId'
        }

        self._financial_institution_id = financial_institution_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreditorAgent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreditorAgent of this CreditorAgent.  # noqa: E501
        :rtype: CreditorAgent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def financial_institution_id(self) -> str:
        """Gets the financial_institution_id of this CreditorAgent.

          # noqa: E501

        :return: The financial_institution_id of this CreditorAgent.
        :rtype: str
        """
        return self._financial_institution_id

    @financial_institution_id.setter
    def financial_institution_id(self, financial_institution_id: str):
        """Sets the financial_institution_id of this CreditorAgent.

          # noqa: E501

        :param financial_institution_id: The financial_institution_id of this CreditorAgent.
        :type financial_institution_id: str
        """
        if financial_institution_id is None:
            raise ValueError("Invalid value for `financial_institution_id`, must not be `None`")  # noqa: E501

        self._financial_institution_id = financial_institution_id
