from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.creditor import Creditor
from openapi_server.models.creditor_account import CreditorAccount
from openapi_server.models.creditor_agent import CreditorAgent
from openapi_server.models.debtor import Debtor
from openapi_server.models.debtor_account import DebtorAccount
from openapi_server.models.instructed_amount import InstructedAmount
from openapi_server.models.payment_identification import PaymentIdentification
from openapi_server.models.transaction_status import TransactionStatus
from openapi_server import util

from openapi_server.models.creditor import Creditor  # noqa: E501
from openapi_server.models.creditor_account import CreditorAccount  # noqa: E501
from openapi_server.models.creditor_agent import CreditorAgent  # noqa: E501
from openapi_server.models.debtor import Debtor  # noqa: E501
from openapi_server.models.debtor_account import DebtorAccount  # noqa: E501
from openapi_server.models.instructed_amount import InstructedAmount  # noqa: E501
from openapi_server.models.payment_identification import PaymentIdentification  # noqa: E501
from openapi_server.models.transaction_status import TransactionStatus  # noqa: E501

class SepaCreditTransferDetailsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, transaction_status=None, payment_id=None, purpose_code=None, requested_execution_date=None, debtor=None, debtor_account=None, creditor_agent=None, creditor=None, creditor_account=None, payment_identification=None, instructed_amount=None, remittance_information_structured=None, remittance_information_unstructured=None):  # noqa: E501
        """SepaCreditTransferDetailsResponse - a model defined in OpenAPI

        :param transaction_status: The transaction_status of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type transaction_status: TransactionStatus
        :param payment_id: The payment_id of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type payment_id: str
        :param purpose_code: The purpose_code of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type purpose_code: str
        :param requested_execution_date: The requested_execution_date of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type requested_execution_date: date
        :param debtor: The debtor of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type debtor: Debtor
        :param debtor_account: The debtor_account of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type debtor_account: DebtorAccount
        :param creditor_agent: The creditor_agent of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type creditor_agent: CreditorAgent
        :param creditor: The creditor of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type creditor: Creditor
        :param creditor_account: The creditor_account of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type creditor_account: CreditorAccount
        :param payment_identification: The payment_identification of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type payment_identification: PaymentIdentification
        :param instructed_amount: The instructed_amount of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type instructed_amount: InstructedAmount
        :param remittance_information_structured: The remittance_information_structured of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type remittance_information_structured: str
        :param remittance_information_unstructured: The remittance_information_unstructured of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :type remittance_information_unstructured: str
        """
        self.openapi_types = {
            'transaction_status': TransactionStatus,
            'payment_id': str,
            'purpose_code': str,
            'requested_execution_date': date,
            'debtor': Debtor,
            'debtor_account': DebtorAccount,
            'creditor_agent': CreditorAgent,
            'creditor': Creditor,
            'creditor_account': CreditorAccount,
            'payment_identification': PaymentIdentification,
            'instructed_amount': InstructedAmount,
            'remittance_information_structured': str,
            'remittance_information_unstructured': str
        }

        self.attribute_map = {
            'transaction_status': 'transactionStatus',
            'payment_id': 'paymentId',
            'purpose_code': 'purposeCode',
            'requested_execution_date': 'requestedExecutionDate',
            'debtor': 'debtor',
            'debtor_account': 'debtorAccount',
            'creditor_agent': 'creditorAgent',
            'creditor': 'creditor',
            'creditor_account': 'creditorAccount',
            'payment_identification': 'paymentIdentification',
            'instructed_amount': 'instructedAmount',
            'remittance_information_structured': 'remittanceInformationStructured',
            'remittance_information_unstructured': 'remittanceInformationUnstructured'
        }

        self._transaction_status = transaction_status
        self._payment_id = payment_id
        self._purpose_code = purpose_code
        self._requested_execution_date = requested_execution_date
        self._debtor = debtor
        self._debtor_account = debtor_account
        self._creditor_agent = creditor_agent
        self._creditor = creditor
        self._creditor_account = creditor_account
        self._payment_identification = payment_identification
        self._instructed_amount = instructed_amount
        self._remittance_information_structured = remittance_information_structured
        self._remittance_information_unstructured = remittance_information_unstructured

    @classmethod
    def from_dict(cls, dikt) -> 'SepaCreditTransferDetailsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SepaCreditTransferDetailsResponse of this SepaCreditTransferDetailsResponse.  # noqa: E501
        :rtype: SepaCreditTransferDetailsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction_status(self) -> TransactionStatus:
        """Gets the transaction_status of this SepaCreditTransferDetailsResponse.


        :return: The transaction_status of this SepaCreditTransferDetailsResponse.
        :rtype: TransactionStatus
        """
        return self._transaction_status

    @transaction_status.setter
    def transaction_status(self, transaction_status: TransactionStatus):
        """Sets the transaction_status of this SepaCreditTransferDetailsResponse.


        :param transaction_status: The transaction_status of this SepaCreditTransferDetailsResponse.
        :type transaction_status: TransactionStatus
        """
        if transaction_status is None:
            raise ValueError("Invalid value for `transaction_status`, must not be `None`")  # noqa: E501

        self._transaction_status = transaction_status

    @property
    def payment_id(self) -> str:
        """Gets the payment_id of this SepaCreditTransferDetailsResponse.

        resource identification of the generated paymentinitiation resource ('Transaction-ID' from the header which is populated with the Intra Bank ID); should be available at least when status is PDNG or ACCP  # noqa: E501

        :return: The payment_id of this SepaCreditTransferDetailsResponse.
        :rtype: str
        """
        return self._payment_id

    @payment_id.setter
    def payment_id(self, payment_id: str):
        """Sets the payment_id of this SepaCreditTransferDetailsResponse.

        resource identification of the generated paymentinitiation resource ('Transaction-ID' from the header which is populated with the Intra Bank ID); should be available at least when status is PDNG or ACCP  # noqa: E501

        :param payment_id: The payment_id of this SepaCreditTransferDetailsResponse.
        :type payment_id: str
        """
        if payment_id is None:
            raise ValueError("Invalid value for `payment_id`, must not be `None`")  # noqa: E501

        self._payment_id = payment_id

    @property
    def purpose_code(self) -> str:
        """Gets the purpose_code of this SepaCreditTransferDetailsResponse.

        ExternalPurpose1Code  # noqa: E501

        :return: The purpose_code of this SepaCreditTransferDetailsResponse.
        :rtype: str
        """
        return self._purpose_code

    @purpose_code.setter
    def purpose_code(self, purpose_code: str):
        """Sets the purpose_code of this SepaCreditTransferDetailsResponse.

        ExternalPurpose1Code  # noqa: E501

        :param purpose_code: The purpose_code of this SepaCreditTransferDetailsResponse.
        :type purpose_code: str
        """
        if purpose_code is None:
            raise ValueError("Invalid value for `purpose_code`, must not be `None`")  # noqa: E501
        if purpose_code is not None and len(purpose_code) > 4:
            raise ValueError("Invalid value for `purpose_code`, length must be less than or equal to `4`")  # noqa: E501
        if purpose_code is not None and len(purpose_code) < 4:
            raise ValueError("Invalid value for `purpose_code`, length must be greater than or equal to `4`")  # noqa: E501

        self._purpose_code = purpose_code

    @property
    def requested_execution_date(self) -> date:
        """Gets the requested_execution_date of this SepaCreditTransferDetailsResponse.

        must match yyyy-MM-dd format, also in CET timezone.  # noqa: E501

        :return: The requested_execution_date of this SepaCreditTransferDetailsResponse.
        :rtype: date
        """
        return self._requested_execution_date

    @requested_execution_date.setter
    def requested_execution_date(self, requested_execution_date: date):
        """Sets the requested_execution_date of this SepaCreditTransferDetailsResponse.

        must match yyyy-MM-dd format, also in CET timezone.  # noqa: E501

        :param requested_execution_date: The requested_execution_date of this SepaCreditTransferDetailsResponse.
        :type requested_execution_date: date
        """
        if requested_execution_date is None:
            raise ValueError("Invalid value for `requested_execution_date`, must not be `None`")  # noqa: E501

        self._requested_execution_date = requested_execution_date

    @property
    def debtor(self) -> Debtor:
        """Gets the debtor of this SepaCreditTransferDetailsResponse.


        :return: The debtor of this SepaCreditTransferDetailsResponse.
        :rtype: Debtor
        """
        return self._debtor

    @debtor.setter
    def debtor(self, debtor: Debtor):
        """Sets the debtor of this SepaCreditTransferDetailsResponse.


        :param debtor: The debtor of this SepaCreditTransferDetailsResponse.
        :type debtor: Debtor
        """
        if debtor is None:
            raise ValueError("Invalid value for `debtor`, must not be `None`")  # noqa: E501

        self._debtor = debtor

    @property
    def debtor_account(self) -> DebtorAccount:
        """Gets the debtor_account of this SepaCreditTransferDetailsResponse.


        :return: The debtor_account of this SepaCreditTransferDetailsResponse.
        :rtype: DebtorAccount
        """
        return self._debtor_account

    @debtor_account.setter
    def debtor_account(self, debtor_account: DebtorAccount):
        """Sets the debtor_account of this SepaCreditTransferDetailsResponse.


        :param debtor_account: The debtor_account of this SepaCreditTransferDetailsResponse.
        :type debtor_account: DebtorAccount
        """
        if debtor_account is None:
            raise ValueError("Invalid value for `debtor_account`, must not be `None`")  # noqa: E501

        self._debtor_account = debtor_account

    @property
    def creditor_agent(self) -> CreditorAgent:
        """Gets the creditor_agent of this SepaCreditTransferDetailsResponse.


        :return: The creditor_agent of this SepaCreditTransferDetailsResponse.
        :rtype: CreditorAgent
        """
        return self._creditor_agent

    @creditor_agent.setter
    def creditor_agent(self, creditor_agent: CreditorAgent):
        """Sets the creditor_agent of this SepaCreditTransferDetailsResponse.


        :param creditor_agent: The creditor_agent of this SepaCreditTransferDetailsResponse.
        :type creditor_agent: CreditorAgent
        """
        if creditor_agent is None:
            raise ValueError("Invalid value for `creditor_agent`, must not be `None`")  # noqa: E501

        self._creditor_agent = creditor_agent

    @property
    def creditor(self) -> Creditor:
        """Gets the creditor of this SepaCreditTransferDetailsResponse.


        :return: The creditor of this SepaCreditTransferDetailsResponse.
        :rtype: Creditor
        """
        return self._creditor

    @creditor.setter
    def creditor(self, creditor: Creditor):
        """Sets the creditor of this SepaCreditTransferDetailsResponse.


        :param creditor: The creditor of this SepaCreditTransferDetailsResponse.
        :type creditor: Creditor
        """
        if creditor is None:
            raise ValueError("Invalid value for `creditor`, must not be `None`")  # noqa: E501

        self._creditor = creditor

    @property
    def creditor_account(self) -> CreditorAccount:
        """Gets the creditor_account of this SepaCreditTransferDetailsResponse.


        :return: The creditor_account of this SepaCreditTransferDetailsResponse.
        :rtype: CreditorAccount
        """
        return self._creditor_account

    @creditor_account.setter
    def creditor_account(self, creditor_account: CreditorAccount):
        """Sets the creditor_account of this SepaCreditTransferDetailsResponse.


        :param creditor_account: The creditor_account of this SepaCreditTransferDetailsResponse.
        :type creditor_account: CreditorAccount
        """
        if creditor_account is None:
            raise ValueError("Invalid value for `creditor_account`, must not be `None`")  # noqa: E501

        self._creditor_account = creditor_account

    @property
    def payment_identification(self) -> PaymentIdentification:
        """Gets the payment_identification of this SepaCreditTransferDetailsResponse.


        :return: The payment_identification of this SepaCreditTransferDetailsResponse.
        :rtype: PaymentIdentification
        """
        return self._payment_identification

    @payment_identification.setter
    def payment_identification(self, payment_identification: PaymentIdentification):
        """Sets the payment_identification of this SepaCreditTransferDetailsResponse.


        :param payment_identification: The payment_identification of this SepaCreditTransferDetailsResponse.
        :type payment_identification: PaymentIdentification
        """

        self._payment_identification = payment_identification

    @property
    def instructed_amount(self) -> InstructedAmount:
        """Gets the instructed_amount of this SepaCreditTransferDetailsResponse.


        :return: The instructed_amount of this SepaCreditTransferDetailsResponse.
        :rtype: InstructedAmount
        """
        return self._instructed_amount

    @instructed_amount.setter
    def instructed_amount(self, instructed_amount: InstructedAmount):
        """Sets the instructed_amount of this SepaCreditTransferDetailsResponse.


        :param instructed_amount: The instructed_amount of this SepaCreditTransferDetailsResponse.
        :type instructed_amount: InstructedAmount
        """
        if instructed_amount is None:
            raise ValueError("Invalid value for `instructed_amount`, must not be `None`")  # noqa: E501

        self._instructed_amount = instructed_amount

    @property
    def remittance_information_structured(self) -> str:
        """Gets the remittance_information_structured of this SepaCreditTransferDetailsResponse.

        recommended to be used in each transaction ; contract related - references to the business; it depends on the client what they want to include  # noqa: E501

        :return: The remittance_information_structured of this SepaCreditTransferDetailsResponse.
        :rtype: str
        """
        return self._remittance_information_structured

    @remittance_information_structured.setter
    def remittance_information_structured(self, remittance_information_structured: str):
        """Sets the remittance_information_structured of this SepaCreditTransferDetailsResponse.

        recommended to be used in each transaction ; contract related - references to the business; it depends on the client what they want to include  # noqa: E501

        :param remittance_information_structured: The remittance_information_structured of this SepaCreditTransferDetailsResponse.
        :type remittance_information_structured: str
        """
        if remittance_information_structured is None:
            raise ValueError("Invalid value for `remittance_information_structured`, must not be `None`")  # noqa: E501
        if remittance_information_structured is not None and len(remittance_information_structured) > 140:
            raise ValueError("Invalid value for `remittance_information_structured`, length must be less than or equal to `140`")  # noqa: E501

        self._remittance_information_structured = remittance_information_structured

    @property
    def remittance_information_unstructured(self) -> str:
        """Gets the remittance_information_unstructured of this SepaCreditTransferDetailsResponse.

        recommended to be used in each transaction ; contract related : references to the business; it depends on the client what they want to include  # noqa: E501

        :return: The remittance_information_unstructured of this SepaCreditTransferDetailsResponse.
        :rtype: str
        """
        return self._remittance_information_unstructured

    @remittance_information_unstructured.setter
    def remittance_information_unstructured(self, remittance_information_unstructured: str):
        """Sets the remittance_information_unstructured of this SepaCreditTransferDetailsResponse.

        recommended to be used in each transaction ; contract related : references to the business; it depends on the client what they want to include  # noqa: E501

        :param remittance_information_unstructured: The remittance_information_unstructured of this SepaCreditTransferDetailsResponse.
        :type remittance_information_unstructured: str
        """
        if remittance_information_unstructured is None:
            raise ValueError("Invalid value for `remittance_information_unstructured`, must not be `None`")  # noqa: E501
        if remittance_information_unstructured is not None and len(remittance_information_unstructured) > 140:
            raise ValueError("Invalid value for `remittance_information_unstructured`, length must be less than or equal to `140`")  # noqa: E501

        self._remittance_information_unstructured = remittance_information_unstructured
