# coding: utf-8

# flake8: noqa
"""
    dbapi-processingOrders

    Create a document processing order. Limited access for special consumers only.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.address import Address
from openapi_client.models.document_metadata import DocumentMetadata
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.natural_person import NaturalPerson
from openapi_client.models.processing_order_metadata import ProcessingOrderMetadata
from openapi_client.models.processing_order_metadata_events_inner import ProcessingOrderMetadataEventsInner
from openapi_client.models.processing_order_metadata_order_form_data import ProcessingOrderMetadataOrderFormData
from openapi_client.models.upload_document_response import UploadDocumentResponse
