# Generated by Django 5.2 on 2025-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='financialinstitution',
            name='financial_institution_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
