from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class CreditorAccount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, iban=None, currency=None):  # noqa: E501
        """CreditorAccount - a model defined in OpenAPI

        :param iban: The iban of this CreditorAccount.  # noqa: E501
        :type iban: str
        :param currency: The currency of this CreditorAccount.  # noqa: E501
        :type currency: str
        """
        self.openapi_types = {
            'iban': str,
            'currency': str
        }

        self.attribute_map = {
            'iban': 'iban',
            'currency': 'currency'
        }

        self._iban = iban
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'CreditorAccount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreditorAccount of this CreditorAccount.  # noqa: E501
        :rtype: CreditorAccount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def iban(self) -> str:
        """Gets the iban of this CreditorAccount.

        The IBAN of this account.  # noqa: E501

        :return: The iban of this CreditorAccount.
        :rtype: str
        """
        return self._iban

    @iban.setter
    def iban(self, iban: str):
        """Sets the iban of this CreditorAccount.

        The IBAN of this account.  # noqa: E501

        :param iban: The iban of this CreditorAccount.
        :type iban: str
        """
        if iban is None:
            raise ValueError("Invalid value for `iban`, must not be `None`")  # noqa: E501
        if iban is not None and not re.search(r'[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}', iban):  # noqa: E501
            raise ValueError(r"Invalid value for `iban`, must be a follow pattern or equal to `/[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}/`")  # noqa: E501

        self._iban = iban

    @property
    def currency(self) -> str:
        """Gets the currency of this CreditorAccount.

        ISO 4217 Alpha 3 currency code.  # noqa: E501

        :return: The currency of this CreditorAccount.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this CreditorAccount.

        ISO 4217 Alpha 3 currency code.  # noqa: E501

        :param currency: The currency of this CreditorAccount.
        :type currency: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501
        if currency is not None and not re.search(r'[A-Z]{3}', currency):  # noqa: E501
            raise ValueError(r"Invalid value for `currency`, must be a follow pattern or equal to `/[A-Z]{3}/`")  # noqa: E501

        self._currency = currency
