# Generated by Django 5.2 on 2025-04-20 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('end_to_end_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('transfer_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('instant', 'Instant')], max_length=20, null=True)),
                ('type_strategy', models.CharField(choices=[('standard_only', 'Standard Only'), ('instant_only', 'Instant Only'), ('instant_if_available', 'Instant If Available')], max_length=20)),
                ('status', models.CharField(choices=[('RJCT', 'RJCT'), ('RCVD', 'RCVD'), ('ACCP', 'ACCP'), ('ACTP', 'ACTP'), ('ACSP', 'ACSP'), ('ACWC', 'ACWC'), ('ACWP', 'ACWP'), ('ACCC', 'ACCC'), ('CANC', 'CANC'), ('PDNG', 'PDNG')], default='PDNG', max_length=20)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=20, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('custom_metadata', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('accounting_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sepa_set', to='accounts.account')),
                ('beneficiary_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.debtor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source_account', models.CharField(max_length=50)),
                ('destination_account', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_iban', models.CharField(max_length=34)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('request_date', models.DateTimeField()),
                ('execution_date', models.DateTimeField()),
                ('accounting_date', models.DateTimeField(blank=True, null=True)),
                ('counterparty_name', models.CharField(max_length=255)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RJCT', 'RJCT'), ('RCVD', 'RCVD'), ('ACCP', 'ACCP'), ('ACTP', 'ACTP'), ('ACSP', 'ACSP'), ('ACWC', 'ACWC'), ('ACWP', 'ACWP'), ('ACCC', 'ACCC'), ('CANC', 'CANC'), ('PDNG', 'PDNG')], default='PDNG', max_length=20)),
                ('custom_id', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_metadata', models.TextField(blank=True, null=True)),
                ('attachment_count', models.IntegerField(default=0)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_set', to='accounts.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
