# Generated by Django 5.2 on 2025-05-09 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('type', models.CharField(choices=[('current_account', 'Current Account'), ('ring_fenced_account', 'Ring-Fenced Account'), ('settlement_account', 'Settlement Account'), ('specially_dedicated_account', 'Specially Dedicated Account'), ('trust_account', 'Trust Account'), ('meal_voucher_account', 'Meal Voucher Account'), ('booster_account', 'Booster Account')], default='current_account', max_length=30)),
                ('is_main', models.CharField(choices=[('main', 'main'), ('virtual', 'virtual')], default='main', max_length=8)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to='authentication.customuser')),
                ('iban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iban')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
