# coding: utf-8

"""
    dbapi-transactionAuthorization

    Accessing sensitive data like ID card information or performing actions such as initiating payments or investment orders need a second factor for authentication (2FA). The Transaction Authorization API lets you easily create proof tokens for 2FA that can be used with other APIs.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_method_type import ChallengeMethodType

class TestChallengeMethodType(unittest.TestCase):
    """ChallengeMethodType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChallengeMethodType(self):
        """Test ChallengeMethodType"""
        # inst = ChallengeMethodType()

if __name__ == '__main__':
    unittest.main()
