# coding: utf-8

"""
    dbapi-transactionAuthorization

    Accessing sensitive data like ID card information or performing actions such as initiating payments or investment orders need a second factor for authentication (2FA). The Transaction Authorization API lets you easily create proof tokens for 2FA that can be used with other APIs.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_request_data_securities_order_modify import ChallengeRequestDataSecuritiesOrderModify

class TestChallengeRequestDataSecuritiesOrderModify(unittest.TestCase):
    """ChallengeRequestDataSecuritiesOrderModify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeRequestDataSecuritiesOrderModify:
        """Test ChallengeRequestDataSecuritiesOrderModify
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeRequestDataSecuritiesOrderModify`
        """
        model = ChallengeRequestDataSecuritiesOrderModify()
        if include_optional:
            return ChallengeRequestDataSecuritiesOrderModify(
                type = 'challengeRequestDataSecuritiesOrderModify',
                order_id = '',
                security_account_id = '048072888001',
                order_limit = openapi_client.models.order_limit.OrderLimit(
                    limit_price = 0, 
                    stop_price = 0, ),
                add_ons = openapi_client.models.order_add_ons.OrderAddOns(
                    expiry_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    restriction = 'GOOD_TILL_DATE', )
            )
        else:
            return ChallengeRequestDataSecuritiesOrderModify(
                type = 'challengeRequestDataSecuritiesOrderModify',
                order_id = '',
                security_account_id = '048072888001',
        )
        """

    def testChallengeRequestDataSecuritiesOrderModify(self):
        """Test ChallengeRequestDataSecuritiesOrderModify"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
