# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ChallengeRequestDataSecuritiesOrderDelete(BaseModel):
    """
    challenge request data for requestType SECURITIES_ORDER_DELETE
    """ # noqa: E501
    type: StrictStr
    order_id: StrictStr = Field(description="Order identifier", alias="orderId")
    security_account_id: Annotated[str, Field(strict=True)] = Field(description="the security account id", alias="securityAccountId")
    __properties: ClassVar[List[str]] = ["type", "orderId", "securityAccountId"]

    @field_validator('security_account_id')
    def security_account_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"[0-9]{12}", value):
            raise ValueError(r"must validate the regular expression /[0-9]{12}/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChallengeRequestDataSecuritiesOrderDelete from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChallengeRequestDataSecuritiesOrderDelete from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type") if obj.get("type") is not None else 'challengeRequestDataSecuritiesOrderDelete',
            "orderId": obj.get("orderId"),
            "securityAccountId": obj.get("securityAccountId")
        })
        return _obj


