# coding: utf-8

"""
    dbapi-processingOrders

    Create a document processing order. Limited access for special consumers only.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.upload_document_response import UploadDocumentResponse

class TestUploadDocumentResponse(unittest.TestCase):
    """UploadDocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadDocumentResponse:
        """Test UploadDocumentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadDocumentResponse`
        """
        model = UploadDocumentResponse()
        if include_optional:
            return UploadDocumentResponse(
                document_reference_id = ''
            )
        else:
            return UploadDocumentResponse(
                document_reference_id = '',
        )
        """

    def testUploadDocumentResponse(self):
        """Test UploadDocumentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
