# Generated by Django 5.2 on 2025-04-24 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sct', '0002_alter_paymentidentification_end_to_end_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepacredittransfer',
            name='payment_identification',
        ),
        migrations.AddField(
            model_name='sepacredittransfer',
            name='end_to_end_id',
            field=models.CharField(blank=True, max_length=36, validators=[django.core.validators.MinLengthValidator(36), django.core.validators.MaxLengthValidator(36)]),
        ),
        migrations.AddField(
            model_name='sepacredittransfer',
            name='instruction_id',
            field=models.CharField(blank=True, max_length=36, validators=[django.core.validators.MinLengthValidator(36), django.core.validators.MaxLengthValidator(36)]),
        ),
    ]
