# coding: utf-8

# flake8: noqa
"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.challenge_method_item import ChallengeMethodItem
from openapi_client.models.challenge_method_mtan import ChallengeMethodMTAN
from openapi_client.models.challenge_method_metadata import ChallengeMethodMetadata
from openapi_client.models.challenge_method_phototan import ChallengeMethodPHOTOTAN
from openapi_client.models.challenge_method_type import ChallengeMethodType
from openapi_client.models.challenge_methods_and_types import ChallengeMethodsAndTypes
from openapi_client.models.challenge_request import ChallengeRequest
from openapi_client.models.challenge_request_data_instant_sepa_credit_transfers import ChallengeRequestDataInstantSepaCreditTransfers
from openapi_client.models.challenge_request_data_securities_order_delete import ChallengeRequestDataSecuritiesOrderDelete
from openapi_client.models.challenge_request_data_securities_order_entry import ChallengeRequestDataSecuritiesOrderEntry
from openapi_client.models.challenge_request_data_securities_order_modify import ChallengeRequestDataSecuritiesOrderModify
from openapi_client.models.challenge_request_data_transfer_partner_legi_data import ChallengeRequestDataTransferPartnerLegiData
from openapi_client.models.challenge_request_switch_method import ChallengeRequestSwitchMethod
from openapi_client.models.challenge_response import ChallengeResponse
from openapi_client.models.challenge_result import ChallengeResult
from openapi_client.models.challenge_start import ChallengeStart
from openapi_client.models.challenge_type_item import ChallengeTypeItem
from openapi_client.models.challenge_type_type import ChallengeTypeType
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.order_activity_type import OrderActivityType
from openapi_client.models.order_add_ons import OrderAddOns
from openapi_client.models.order_limit import OrderLimit
