# coding: utf-8

# flake8: noqa
"""
    dbapi-transactionAuthorization

    Accessing sensitive data like ID card information or performing actions such as initiating payments or investment orders need a second factor for authentication (2FA). The Transaction Authorization API lets you easily create proof tokens for 2FA that can be used with other APIs.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.challenge_method_item import ChallengeMethodItem
from openapi_client.models.challenge_method_mtan import ChallengeMethodMTAN
from openapi_client.models.challenge_method_metadata import ChallengeMethodMetadata
from openapi_client.models.challenge_method_phototan import ChallengeMethodPHOTOTAN
from openapi_client.models.challenge_method_type import ChallengeMethodType
from openapi_client.models.challenge_methods_and_types import ChallengeMethodsAndTypes
from openapi_client.models.challenge_request import ChallengeRequest
from openapi_client.models.challenge_request_data_instant_sepa_credit_transfers import ChallengeRequestDataInstantSepaCreditTransfers
from openapi_client.models.challenge_request_data_securities_order_delete import ChallengeRequestDataSecuritiesOrderDelete
from openapi_client.models.challenge_request_data_securities_order_entry import ChallengeRequestDataSecuritiesOrderEntry
from openapi_client.models.challenge_request_data_securities_order_modify import ChallengeRequestDataSecuritiesOrderModify
from openapi_client.models.challenge_request_data_securities_order_session import ChallengeRequestDataSecuritiesOrderSession
from openapi_client.models.challenge_request_data_sepa_payment import ChallengeRequestDataSepaPayment
from openapi_client.models.challenge_request_data_transfer_partner_legi_data import ChallengeRequestDataTransferPartnerLegiData
from openapi_client.models.challenge_request_switch_method import ChallengeRequestSwitchMethod
from openapi_client.models.challenge_response import ChallengeResponse
from openapi_client.models.challenge_result import ChallengeResult
from openapi_client.models.challenge_start import ChallengeStart
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.error_response2 import ErrorResponse2
from openapi_client.models.order_activity_type import OrderActivityType
from openapi_client.models.order_add_ons import OrderAddOns
from openapi_client.models.order_limit import OrderLimit
