# coding: utf-8

"""
    dbapi-sepaCreditTransfer

    Easily initiate SEPA credit transfer then if required cancel or get the status and get the details afterwards.

    The version of the OpenAPI document: v1
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransactionStatus(str, Enum):
    """
    Specifies the status of a transaction in a coded form based on SEPA Rulebook: AT-R1 The type of R-message 'RJCT’ in case of a negative confirmation or reject, or 'ACCP' in case of a positive confirmation. 'PDNG' value is possible in case Payment Order Response is sent for not yet rejected transaction
    """

    """
    allowed enum values
    """
    RJCT = 'RJCT'
    RCVD = 'RCVD'
    ACCP = 'ACCP'
    ACTC = 'ACTC'
    ACSP = 'ACSP'
    ACSC = 'ACSC'
    ACWC = 'ACWC'
    ACWP = 'ACWP'
    ACCC = 'ACCC'
    CANC = 'CANC'
    PDNG = 'PDNG'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransactionStatus from a JSON string"""
        return cls(json.loads(json_str))


