# Generated by Django 5.2 on 2025-04-21 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('message', models.TextField()),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_institution_id', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_to_end_id', models.CharField(max_length=35)),
                ('instruction_id', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('zip_code_and_city', models.CharField(max_length=100)),
                ('street_and_house_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('postal_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtor_addresses', to='gpt.postaladdress')),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('postal_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditor_addresses', to='gpt.postaladdress')),
            ],
        ),
        migrations.CreateModel(
            name='SepaCreditTransfer',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_id', models.UUIDField(default=uuid.uuid4)),
                ('transaction_status', models.CharField(choices=[('PDNG', 'Pendiente'), ('ACSC', 'Aceptado'), ('RJCT', 'Rechazado'), ('CANC', 'Cancelado')], default='PDNG', max_length=10)),
                ('purpose_code', models.CharField(blank=True, max_length=4, null=True)),
                ('requested_execution_date', models.DateField(blank=True, null=True)),
                ('remittance_information_structured', models.CharField(blank=True, max_length=140, null=True)),
                ('remittance_information_unstructured', models.CharField(blank=True, max_length=140, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_transfers', to='gpt.creditor')),
                ('creditor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_accounts', to='gpt.account')),
                ('creditor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpt.financialinstitution')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_transfers', to='gpt.debtor')),
                ('debtor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_accounts', to='gpt.account')),
                ('instructed_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt.amount')),
                ('payment_identification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpt.paymentidentification')),
            ],
        ),
    ]
