# Generated by Django 5.2 on 2025-04-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidentification',
            name='end_to_end_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='paymentidentification',
            name='instruction_id',
            field=models.CharField(max_length=36),
        ),
    ]
