# Generated by Django 5.2 on 2025-04-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_alter_account_iban_alter_creditor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditor',
            old_name='name',
            new_name='creditor_name',
        ),
        migrations.RenameField(
            model_name='debtor',
            old_name='name',
            new_name='debtor_name',
        ),
    ]
