# Generated by Django 5.2 on 2025-04-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_alter_paymentidentification_end_to_end_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentidentification',
            name='end_to_end_id',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='paymentidentification',
            name='instruction_id',
            field=models.CharField(max_length=35),
        ),
    ]
