# Generated by Django 5.2 on 2025-05-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('postal_address_country', models.CharField(max_length=2)),
                ('postal_address_street', models.CharField(max_length=70, unique=True)),
                ('postal_address_city', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CreditorAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(max_length=11, unique=True)),
                ('financial_institution_id', models.CharField(max_length=35, unique=True)),
                ('other_information', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('customer_id', models.CharField(max_length=35, unique=True)),
                ('postal_address_country', models.CharField(max_length=2)),
                ('postal_address_street', models.CharField(max_length=70, unique=True)),
                ('postal_address_city', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_to_end_id', models.CharField(max_length=35)),
                ('instruction_id', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='CreditorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditoraccount_set', to='gpt4.creditor')),
            ],
        ),
        migrations.CreateModel(
            name='DebtorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.debtor')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=36, unique=True)),
                ('instructed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('purpose_code', models.CharField(default='GDSV', max_length=4)),
                ('requested_execution_date', models.DateField()),
                ('remittance_information_structured', models.CharField(blank=True, max_length=10, null=True)),
                ('remittance_information_unstructured', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada técnicamente'), ('ACSP', 'En proceso'), ('ACSC', 'Ejecutada con éxito'), ('ACWC', 'Con advertencia'), ('ACWP', 'Pendiente de aprobación'), ('ACCC', 'Concluida'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente'), ('CREA', 'Creada')], default='CREA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.creditor')),
                ('creditor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.creditoraccount')),
                ('creditor_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.creditoragent')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.debtor')),
                ('debtor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.debtoraccount')),
                ('payment_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.paymentidentification')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(upload_to='logs/transferencias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt4.transfer')),
            ],
        ),
    ]
