# Generated by Django 5.2 on 2025-05-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoraccount',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='customer_id',
            field=models.CharField(default='090512DEUTDEFFXXX886479', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='name',
            field=models.CharField(default='MIRYA TRADING CO LTD', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='postal_address_city',
            field=models.CharField(default='60325 FRANKFURT', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='postal_address_country',
            field=models.CharField(default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='postal_address_street',
            field=models.CharField(default='TAUNUSANLAGE 12', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='debtoraccount',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='debtoraccount',
            name='iban',
            field=models.CharField(default='DE86500700100925993805', max_length=34, unique=True),
        ),
    ]
