# coding: utf-8

"""
    dbapi-onetimepasswords

    One-Time Passwords API. Please also refer to the Transaction Authorization API which covers even more use cases.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ChallengeMethodType(str, Enum):
    """
    Challenge method
    """

    """
    allowed enum values
    """
    MTAN = 'MTAN'
    PHOTOTAN = 'PHOTOTAN'
    PUSHTAN = 'PUSHTAN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChallengeMethodType from a JSON string"""
        return cls(json.loads(json_str))


