# Generated by Django 5.2 on 2025-05-01 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scheme', models.CharField(choices=[('b2b', 'B2B'), ('core', 'CORE')], max_length=4)),
                ('signature_date', models.DateField()),
                ('contract_reference', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('debtor_iban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates_by_iban', to='core.debtor', to_field='iban')),
                ('debtor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates_by_name', to='core.debtor', to_field='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('message', models.CharField(blank=True, max_length=20, null=True)),
                ('end_to_end_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_note', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_metadata', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('local_iban', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', to_field='name')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='collection.mandate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
