# coding: utf-8

"""
    dbapi-processingOrders

    Create a document processing order. Limited access for special consumers only.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.natural_person import NaturalPerson

class TestNaturalPerson(unittest.TestCase):
    """NaturalPerson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NaturalPerson:
        """Test NaturalPerson
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NaturalPerson`
        """
        model = NaturalPerson()
        if include_optional:
            return NaturalPerson(
                noncustomer = True,
                first_name = '',
                last_name = '',
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return NaturalPerson(
                first_name = '',
                last_name = '',
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testNaturalPerson(self):
        """Test NaturalPerson"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
