# coding: utf-8

"""
    dbapi-processingOrders

    Create a document processing order. Limited access for special consumers only.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_metadata import DocumentMetadata

class TestDocumentMetadata(unittest.TestCase):
    """DocumentMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentMetadata:
        """Test DocumentMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentMetadata`
        """
        model = DocumentMetadata()
        if include_optional:
            return DocumentMetadata(
                document_name = '',
                document_reference_id = '',
                document_type = 'CAPITAL_GAINS_TAX',
                document_sub_type = 'SECURITY_ACCOUNTS_OPENING'
            )
        else:
            return DocumentMetadata(
                document_type = 'CAPITAL_GAINS_TAX',
                document_sub_type = 'SECURITY_ACCOUNTS_OPENING',
        )
        """

    def testDocumentMetadata(self):
        """Test DocumentMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
