# coding: utf-8

"""
    dbapi-transactionAuthorization

    Accessing sensitive data like ID card information or performing actions such as initiating payments or investment orders need a second factor for authentication (2FA). The Transaction Authorization API lets you easily create proof tokens for 2FA that can be used with other APIs.

    The version of the OpenAPI document: v2
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.challenge_request_data_transfer_partner_legi_data import ChallengeRequestDataTransferPartnerLegiData

class TestChallengeRequestDataTransferPartnerLegiData(unittest.TestCase):
    """ChallengeRequestDataTransferPartnerLegiData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeRequestDataTransferPartnerLegiData:
        """Test ChallengeRequestDataTransferPartnerLegiData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeRequestDataTransferPartnerLegiData`
        """
        model = ChallengeRequestDataTransferPartnerLegiData()
        if include_optional:
            return ChallengeRequestDataTransferPartnerLegiData(
                type = 'challengeRequestDataTransferPartnerLegiData'
            )
        else:
            return ChallengeRequestDataTransferPartnerLegiData(
                type = 'challengeRequestDataTransferPartnerLegiData',
        )
        """

    def testChallengeRequestDataTransferPartnerLegiData(self):
        """Test ChallengeRequestDataTransferPartnerLegiData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
