# coding: utf-8

"""
    dbapi-sepaCreditTransfer

    Easily initiate SEPA credit transfer then if required cancel or get the status and get the details afterwards.

    The version of the OpenAPI document: v1
    Contact: bank.api@db.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.delete_sepa_credit_transfer_api import DeleteSepaCreditTransferApi


class TestDeleteSepaCreditTransferApi(unittest.TestCase):
    """DeleteSepaCreditTransferApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeleteSepaCreditTransferApi()

    def tearDown(self) -> None:
        pass

    def test_payment_id_delete(self) -> None:
        """Test case for payment_id_delete

        Cancel the Sepa Credit Transfer
        """
        pass


if __name__ == '__main__':
    unittest.main()
