# Generated by Django 5.2 on 2025-04-29 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('street_and_house_number', models.CharField(max_length=70)),
                ('zip_code_and_city', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_institution_id', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='GroupHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=35)),
                ('number_of_transactions', models.IntegerField()),
                ('control_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('initiating_party_name', models.CharField(max_length=70)),
                ('create_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstructedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_to_end_id', models.CharField(max_length=35)),
                ('instruction_id', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTypeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level_code', models.CharField(choices=[('SEPA', 'SEPA estándar'), ('URGENT', 'Urgente'), ('INST', 'SEPA Instantánea')], max_length=10)),
                ('local_instrument_code', models.CharField(blank=True, choices=[('INST', 'SEPA Instantáneo'), ('CORE', 'Adeudo Directo SEPA CORE'), ('B2B', 'Adeudo Directo SEPA B2B'), ('URGP', 'Pago Urgente Europeo')], max_length=35, null=True)),
                ('category_purpose_code', models.CharField(blank=True, choices=[('SALA', 'Salario'), ('TAXS', 'Impuestos'), ('SUPP', 'Proveedores'), ('CORT', 'Pago de préstamo'), ('GDSV', 'Bienes y servicios')], max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(max_length=70)),
                ('postal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.address')),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=140)),
                ('customer_id', models.CharField(max_length=35, unique=True)),
                ('postal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.address')),
            ],
        ),
        migrations.CreateModel(
            name='BulkTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=35, unique=True)),
                ('transaction_status', models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada técnicamente'), ('ACSP', 'En proceso'), ('ACSC', 'Ejecutada con éxito'), ('ACWC', 'Con advertencia'), ('ACWP', 'Pendiente de aprobación'), ('ACCC', 'Concluida'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.groupheader')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_information_id', models.CharField(max_length=35)),
                ('payment_method', models.CharField(max_length=35)),
                ('batch_booking', models.BooleanField(default=True)),
                ('number_of_transactions', models.IntegerField()),
                ('control_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_execution_date', models.DateField()),
                ('charge_bearer', models.CharField(max_length=35)),
                ('bulk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_informations', to='gpt3.bulktransfer')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.debtor')),
                ('debtor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.account')),
                ('debtor_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.financialinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransfersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remittance_information_unstructured', models.CharField(blank=True, max_length=140, null=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.creditor')),
                ('creditor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.account')),
                ('creditor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpt3.financialinstitution')),
                ('instructed_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.instructedamount')),
                ('payment_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.paymentidentification')),
                ('payment_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfers', to='gpt3.paymentinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SepaCreditTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=36, unique=True)),
                ('auth_id', models.CharField(blank=True, max_length=70, null=True)),
                ('transaction_status', models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada técnicamente'), ('ACSP', 'En proceso'), ('ACSC', 'Ejecutada con éxito'), ('ACWC', 'Con advertencia'), ('ACWP', 'Pendiente de aprobación'), ('ACCC', 'Concluida'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente')], default='PDNG', max_length=10)),
                ('purpose_code', models.CharField(default='GDSV', max_length=4)),
                ('requested_execution_date', models.DateField()),
                ('remittance_information_structured', models.CharField(blank=True, max_length=10, null=True)),
                ('remittance_information_unstructured', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.creditor')),
                ('creditor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_account', to='gpt3.account')),
                ('creditor_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.financialinstitution')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.debtor')),
                ('debtor_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_account', to='gpt3.account')),
                ('instructed_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.instructedamount')),
                ('payment_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.paymentidentification')),
                ('payment_type_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpt3.paymenttypeinformation')),
            ],
        ),
    ]
