# Generated by Django 5.2 on 2025-05-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepacredittransfer',
            name='payment_type_information',
        ),
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='auth_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentTypeInformation',
        ),
    ]
