# Generated by Django 5.2 on 2025-04-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='transaction_status',
            field=models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada técnicamente'), ('ACSP', 'En proceso'), ('ACSC', 'Ejecutada con éxito'), ('ACWC', 'Con advertencia'), ('ACWP', 'Pendiente de aprobación'), ('ACCC', 'Concluida'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente'), ('ERRO', 'Error'), ('CREA', 'Creada')], default='PDNG', max_length=10),
        ),
    ]
