# Generated by Django 5.2 on 2025-04-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTypeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level_code', models.CharField(choices=[('SEPA', 'SEPA estándar'), ('URGENT', 'Urgente'), ('INST', 'SEPA Instantánea')], default='INST', max_length=10)),
                ('local_instrument_code', models.CharField(blank=True, choices=[('INST', 'SEPA Instantáneo'), ('CORE', 'Adeudo Directo SEPA CORE'), ('B2B', 'Adeudo Directo SEPA B2B'), ('URGP', 'Pago Urgente Europeo')], default='INST', max_length=35, null=True)),
                ('category_purpose_code', models.CharField(blank=True, choices=[('SALA', 'Salario'), ('TAXS', 'Impuestos'), ('SUPP', 'Proveedores'), ('CORT', 'Pago de préstamo'), ('GDSV', 'Bienes y servicios')], default='GDSV', max_length=35, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='purpose_code',
            field=models.CharField(default='GDSV', max_length=4),
        ),
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='instructed_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.amount'),
        ),
        migrations.AddField(
            model_name='sepacredittransfer',
            name='payment_type_information',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpt3.paymenttypeinformation'),
        ),
    ]
