# Generated by Django 5.2 on 2025-04-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0002_amount_paymenttypeinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
