# Generated by Django 5.2 on 2025-04-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0003_alter_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='instructed_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpt3.instructedamount'),
        ),
        migrations.AlterField(
            model_name='instructedamount',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
