# Generated by Django 5.2 on 2025-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0004_alter_sepacredittransfer_instructed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructedamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
