# Generated by Django 5.2 on 2025-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0005_alter_instructedamount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='payment_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
