# Generated by Django 5.2 on 2025-04-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0006_alter_sepacredittransfer_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='payment_type_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpt3.paymenttypeinformation'),
        ),
    ]
