# Generated by Django 5.2 on 2025-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0007_alter_sepacredittransfer_payment_type_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttypeinformation',
            name='category_purpose_code',
            field=models.CharField(blank=True, choices=[('SALA', 'Salario'), ('TAXS', 'Impuestos'), ('SUPP', 'Proveedores'), ('CORT', 'Pago de préstamo'), ('GDSV', 'Bienes y servicios')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttypeinformation',
            name='local_instrument_code',
            field=models.CharField(blank=True, choices=[('INST', 'SEPA Instantáneo'), ('CORE', 'Adeudo Directo SEPA CORE'), ('B2B', 'Adeudo Directo SEPA B2B'), ('URGP', 'Pago Urgente Europeo')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttypeinformation',
            name='service_level_code',
            field=models.CharField(choices=[('SEPA', 'SEPA estándar'), ('URGENT', 'Urgente'), ('INST', 'SEPA Instantánea')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='remittance_information_structured',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='remittance_information_unstructured',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
