# Generated by Django 5.2 on 2025-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt3', '0008_alter_paymenttypeinformation_category_purpose_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepacredittransfer',
            name='remittance_information_structured',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
