# Generated by Django 5.2 on 2025-05-09 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepa2',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to='authentication.customuser'),
        ),
        migrations.AlterField(
            model_name='sepa3',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to='authentication.customuser'),
        ),
    ]
